version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - RABBITMQ_HOSTNAME=ambev_developer_evaluation_rabbitmq
      - RABBITMQ_USERNAME=DeveloperStore
      - RABBITMQ_PASSWORD=DeveloperStore
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - ambev.developerevaluation.database
      - ambev.developerevaluation.rabbitmq

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13
    environment:
      POSTGRES_DB: DeveloperStore
      POSTGRES_USER: DeveloperStore
      POSTGRES_PASSWORD: DeveloperStore
    ports:
      - "5432:5432"
    restart: unless-stopped

  ambev.developerevaluation.rabbitmq:
    container_name: ambev_developer_evaluation_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: DeveloperStore
      RABBITMQ_DEFAULT_PASS: DeveloperStore
    ports:
      - "5672:5672"
      - "15672:15672"